server:
  port: 8081
  
spring:
  application:
    name: webapp-service

eureka:
  instance:
    instance-id: webapp-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka