server:
  port: 8084

eureka:
  instance:
    instance-id: order-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/waw?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 'Ckdals0540@'
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

logging.level:
  org.hibernate.SQL: debug
