server:
  port: 8083
  
spring:
  application:
    name: product-service

eureka:
  instance:
    instance-id: product-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka