server:
  port: 8083

eureka:
  instance:
    instance-id: product-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/waw?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '!!kdk236'
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

logging.level:
  org.hibernate.SQL: debug
