server:
  port: 8083

eureka:
  instance:
    instance-id: product-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/waw?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '!!kdk236'
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kdk
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging.level:
  org.hibernate.SQL: debug
